### ISSUE TITLE
Aggregates pr feedback checklist

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb_next#44]
- [ ] ~`filter` instead of if statement: https://github.com/GlareDB/rayexec/pull/35#discussion_r1600534223~
- [x] More readable generics: https://github.com/GlareDB/rayexec/pull/35#discussion_r1600534604 and https://github.com/GlareDB/rayexec/pull/35#discussion_r1600579731
- [ ] More docs around `GroupedStates`: https://github.com/GlareDB/rayexec/pull/35#discussion_r1600579898
- [ ] Pull out covar impl to its own function, name `covariance`: https://github.com/GlareDB/rayexec/pull/35#discussion_r1600580526
- [ ] `remaining == 0`: https://github.com/GlareDB/rayexec/pull/35#discussion_r1599298073
- [x] Remove unneeded enumerate: https://github.com/GlareDB/rayexec/pull/35#discussion_r1600575124
